### ISSUE TITLE
Add example about Endo functions

### ISSUE THREAD

**Issue by julien-truffaut** [fp-tower/foundation#10]
e.g. show that the builder pattern is just composition of Endo function

https://dzone.com/articles/design-patterns-the-builder-pattern

**Comment by phderome** [comment]
Looks like usage of https://julien-truffaut.github.io/fp-foundation/Typeclass.html#54 point towards a solution with `inc`, `double` representing endo functions and `func` using monoFoldLeft representing the builder expression that takes the list of functions to compose.

Although syntactically, I don't immediately see the correspondance. Is the intent to present the same API style as Builder pattern but perhaps using folds and monoid on function that combine through composition?

**Comment by julien-truffaut** [comment]
What I would like to show is that the builder pattern e.g.

```
HttpServerBuilder
  .withPort(9000)
  .withRoutes(...)
  .withExecutor(...)
  .build()
```

is just composition of endo function. So yes, it could be done using `foldMap` and `Endo` `Monoid` but it is chapter 3 but the main point I want to pass is that composition of function allow very elegant API and they are already familiar with it (even though they may not have realised)
