### ISSUE TITLE
Slide 50 review should Applicative inherit from Apply?

### ISSUE THREAD

**Issue by phderome** [fp-tower/foundation#45]
as headline says.

**Comment by julien-truffaut** [comment]
Yes, it should but I wanted to simplify the hierarchy by first presenting Functor/Applicative/Monad. Then in the exercises, people will discover why we may want more granular typeclasses (e.g. Apply and FlatMap). One of the last slide shows the granularity of cats typeclasses. 

I also want to add some slides about the fact that Applicative was discovered recently (circa 2008) and this year, there was a paper about introducing a new typeclass between Applicative and Monad.

**Comment by phderome** [comment]
Very interesting.

**Comment by julien-truffaut** [comment]
moved to https://github.com/fp-tower/abstraction
